name: Deploy

on:
    push: 
        branches:
            - main

jobs:
    build-deploy:
        name: build and deploy application
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Setup Java 21
              uses: actions/setup-java@v3
              with: 
                  distribution: "tem"
                  java-version: 21.0.2
            
            - name: build application
              run: |
                  mvn clean
                  mvn -B package --file pom.xml