name: Deploy

on:
    push: 
        branches:
            - main

jobs:
    build-deploy:
        name: Build and Deploy application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin' # See 'Supported distributions' for available options
                  java-version: '21'
            
            - name: Build Application
              run: |
                  mvn clean
                  mvn -B package --file pom.xml
            
            - name: Build Docker Image
              uses: actions/build-push-actions@v5
              with:
                context: .
                dockerfile: Dockerfile
                push: false
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops-playground:latest
            
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Push to Docker Hub
              uses: docker/build-push-actions@v5
              with:
                context: .
                dockerfile: Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops-playground:latest