name: Deploy

on:
    push: 
        branches:
            - main

jobs:
    build-deploy:
        name: build and deploy application
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Setup Java 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin' # See 'Supported distributions' for available options
                  java-version: '21'
            
            - name: build application
              run: |
                  mvn clean
                  mvn -B package --file pom.xml